# Generated by Django 4.1.7 on 2023-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tittle", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="portfolio/images")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
